version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      MONGO_URI: mongodb://mongo:27017/creditdb
      PORT: 5000
      BOT_PROCESS_URL: http://bot:6000/api/bot/process
      BOT_START_URL: http://bot:6000/start
      APP_MODE: real
      JWT_SECRET: supersecret
      ADMIN_USER: admin
      ADMIN_PASS: change-me
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: bucket
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - bot

  bot:
    build: ./bot_service
    environment:
      PORT: 6000
      BACKEND_URL: http://backend:5000
      BOT_TOKEN: token
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: bucket
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "6000:6000"
    depends_on:
      - mongo

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./credit-dashboard:/app
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
