version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    environment:
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      BOT_PROCESS_URL: ${BOT_PROCESS_URL}
      BOT_START_URL: ${BOT_START_URL}
      APP_MODE: ${APP_MODE}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS_HASH: ${ADMIN_PASS_HASH}
      BOT_TOKEN: ${BOT_TOKEN}
      ENABLE_CRON: ${ENABLE_CRON:-false}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - bot

  bot:
    build: ./bot_service
    environment:
      PORT: ${PORT_BOT:-6000}
      BACKEND_URL: ${BACKEND_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "6000:6000"
    depends_on:
      - mongo

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./credit-dashboard:/app
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    environment:
      REACT_APP_BACKEND_URL: ${BACKEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
